"""
Cutscenes - Sora-Powered FMV Omen System

Turns rare simulation events into Full Motion Video cutscenes.

The mall doesn't just simulate - it REMEMBERS. When specific conditions occur
(Janitor breaks rule, Cloud crosses threshold, Toddler manifests), the engine
triggers cinematic moments generated by Sora.

Usage:
    from cutscenes import CutsceneEngine, SimulationEvent, handle_event

    # Initialize engine
    engine = CutsceneEngine(cutscene_dir="data/cutscenes")
    engine.load_all()

    # In sim loop
    if janitor.breaks_rule():
        event = SimulationEvent("JANITOR_RULE_BROKEN", zone=janitor.zone)
        handle_event(event, get_sim_state(), engine, current_time)
"""

from .cutscene_engine import (
    CutsceneDefinition,
    CutsceneEngine,
    CutsceneTrigger,
    PlaybackDecision,
    ReplayPolicy,
    SimulationEvent,
    SoraPrompt,
    handle_event,
)

__all__ = [
    "CutsceneDefinition",
    "CutsceneEngine",
    "CutsceneTrigger",
    "PlaybackDecision",
    "ReplayPolicy",
    "SimulationEvent",
    "SoraPrompt",
    "handle_event",
]
